---
- import_playbook: inventory.yml


- name: destroy kvm guests

  hosts: guests

  gather_facts: no

  become: yes

  vars_files:
    - vars.yml

  tasks:

    - block:

        - name: destroy kvm guest
          virt:
            command: destroy
            name: "{{ inventory_hostname }}"
          failed_when: false

        - name: undefine kvm guest
          virt:
            command: undefine
            name: "{{ inventory_hostname }}"
          failed_when: false

        - name: destroy kvm guest disks
          file:
            path: "{{ guest_disk }}"
            state: absent
          vars:
            guest_disk: "{{ cache_dir }}/{{ inventory_hostname }}.img"

        - name: destroy kvm guest extra disks
          file:
            path: "{{ guest_disk }}"
            state: absent
          vars:
            guest_disk: "{{ cache_dir }}/{{ inventory_hostname }}.add.img"

      delegate_to: "{{ groups['molecule'] | first }}"


- name: destroy kvm guests

  hosts: molecule

  become: yes

  vars_files:
    - vars.yml

  tasks:

    - name: dnat ssh preroute
      iptables:
        table: nat
        chain: PREROUTING
        destination_port: "{{ (ssh_port_base | int) + (port_offset | int) }}"
        to_destination: "{{ item.installer_interface.ipaddress }}:22"
        jump: DNAT
        protocol: tcp
        state: absent
      loop_control:
        index_var: port_offset
        label: "{{ item.installer_hostname }}"
      loop: "{{ guests }}"

    - name: dnat ssh output
      iptables:
        table: nat
        chain: OUTPUT
        destination_port: "{{ (ssh_port_base | int) + (port_offset | int) }}"
        to_destination: "{{ item.installer_interface.ipaddress }}:22"
        jump: DNAT
        protocol: tcp
        state: absent
      loop_control:
        index_var: port_offset
        label: "{{ item.installer_hostname }}"
      loop: "{{ guests }}"

    - name: unmasquerade bridge
      iptables:
        table: nat
        chain: POSTROUTING
        out_interface: "{{ ansible_default_ipv4.interface }}"
        source: "{{ bridge_net }}"
        destination: 0.0.0.0/0
        jump: MASQUERADE
        protocol: all
        state: present

    - name: destroy dummy bridge
      command: "nmcli con del {{ bridge_name }}"
      failed_when: false

    - name: destroy dummy interface
      command: "ip link del {{ iface_name }}"
      failed_when: false
