---
- import_playbook: inventory.yml


- name: reboot guest

  hosts: guests

  become: yes

  vars_files:
    - ./vars.yml

  pre_tasks:

    - name: wait for pending tasks to complete
      pause:
        seconds: 30

    - name: shut down guest
      command: /sbin/shutdown -h now

    - name: wait for shutdown to complete
      pause:
        seconds: 30

  tasks:

    - block:

        - name: stop kvm guest
          virt:
            name: "{{ inventory_hostname }}"
            command: destroy
          failed_when: false

        - name: start kvm guest
          virt:
            name: "{{ inventory_hostname }}"
            state: running

      delegate_to: "{{ groups['molecule'] | first }}"

    - name: wait for connection
      wait_for_connection:
