---
dependency:
  name: galaxy
  options:
    role-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml
    requirements-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml
driver:
  name: delegated
platforms:
  - name: instance
    user: ubuntu
    image: ami-03d315ad33b9d49c4
    instance_type: c5d.metal
    subnet_id: subnet-d2a31c8b
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      host_key_checking: false
  playbooks:
    converge: ../converge.yml
    verify: ../verify.yml
    prepare: ../prepare.yml
    create: ../create.yml
    destroy: ../destroy.yml
    cleanup: ../cleanup.yml
    side_effect: ../reboot.yml
  inventory:
    group_vars:
      all:
        aws_provision: yes
        aws_project_name: nephelaiio.growfs
        aws_env_name: ${MOLECULE_SCENARIO_NAME}
        aws_env_region: us-east-1
        growfs_device_filter: "vd*"
verifier:
  name: ansible
scenario:
  converge_sequence:
    - converge
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - destroy
